name: CI/CD Pipeline (Testing Only)

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to DockerHub (Testing)
        run: |
          echo "Logging in to DockerHub..."
          docker login -u alavalapatikishroe -p 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

      - name: Build and Push Docker Image
        run: |
          docker build -t alavalapatikishore/employee-login-app:latest .
          docker push alavalapatikishore/employee-login-app:latest
